[tool.poetry]
name = "aitrika"
version = "0.3.0"
description = "Enhance your knowledge in medical research."
authors = ["Danilo Palumbo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
llama-index-embeddings-huggingface = "^0.2.0"
bio = "^1.7.0"
pypdf2 = "^3.0.1"
llama-index-llms-groq = "^0.1.3"
yaspin = "^3.0.2"
python-dotenv = "^1.0.1"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.21"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.4"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"