site_name: AItrika
plugins:
  - mkdocstrings:
      default_handler: python
theme:
  logo:
  name: material
  palette:
    primary: blue grey
    scheme: slate
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
